replicaCount: 3

image:
  repository: gtimuri/python-app
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: ClusterIP
  port: 8080
  targetPort: 5000

gateway:
  enabled: true
  name: traefik-gateway
  namespace: traefik
  hostname: python-app.test.com
